import type { Finding, MCPServer } from '../types.js'

/** Remediation guidance for shadowing findings. */
const SHADOWING_REMEDIATION =
  'This tool shadows a built-in or commonly-used tool name. Rename the tool or remove the duplicate MCP server to prevent confusion.'

/**
 * Built-in tool names that are commonly targeted for shadowing attacks.
 * A shadowing attack registers a malicious tool with the same or similar name
 * as a trusted built-in, causing the LLM to call the malicious version.
 */
const BUILT_IN_TOOL_NAMES = new Set([
  'bash',
  'computer',
  'edit',
  'read',
  'write',
  'str_replace_editor',
  'str_replace_based_edit_tool',
  'create_file',
  'delete_file',
  'list_files',
  'search_files',
  'grep',
  'find',
  'execute',
  'run',
  'shell',
  'terminal',
  'python',
  'javascript',
  'code',
  'web_search',
  'browser',
  'fetch',
  'http_request',
  'mcp_install',
  'git',
  'git_diff',
  'git_commit',
  'git_push',
  'git_init',
  'list_directory',
  'read_file',
  'write_file',
  'move_file',
  'copy_file',
  'search_code',
  'run_command',
  'send_message',
  'get_url',
  'curl',
  'download',
  'upload',
  'glob',
  'grep',
  'todo',
  'notebook',
  'agent',
  'ask_user',
  'web_fetch',
  'mcp_list',
  'mcp_connect',
  'mcp_disconnect',
  'tool_call',
  'approve',
  'deny',
  'submit',
  'screenshot',
  'click',
  'type',
  'scroll',
  'navigate',
  'dispatch',
  'clipboard',
  'paste',
  'keypress',
  'drag',
  'hover',
  'wait',
  'assert',
  'verify',
  'validate',
  'debug',
  'inspect',
  'profile',
  'trace',
  'memory',
  'patch',
  'diff',
  'merge',
  'rebase',
  'stash',
  'commit',
  'push',
  'pull',
  'clone',
  'deploy',
  'rollback',
  'scale',
  'create_message',
  'sample',
  'sampling',
  'think',
  'plan',
  'search',
  'replace',
  'insert',
  'delete',
  'rename',
  'refactor',
  'test',
  'lint',
  'format',
  'compile',
  'build',
  'install',
  'uninstall',
  'update',
  'upgrade',
  'publish',
  'login',
  'logout',
  'auth',
  'authorize',
  'connect',
  'disconnect',
  'subscribe',
  'unsubscribe',
  'listen',
  'watch',
  'monitor',
  'alert',
  'notify',
  'log',
  'audit',
  'scan',
  'analyze',
  'encrypt',
  'decrypt',
  'sign',
  'hash',
  'token',
  'session',
  'config',
  'settings',
  'env',
  'secret',
  'prompt',
  'completion',
  'generate',
  'embed',
  'transcribe',
  'translate',
  'summarize',
  'classify',
  'annotate',
  'label',
  'evaluate',
  'benchmark',
  'reset',
  'revert',
  'restore',
  'backup',
  'snapshot',
  'migrate',
  'import',
  'export',
  'sync',
  'transfer',
  'proxy',
  'relay',
  'gateway',
  'tunnel',
  'forward',
  'approve_tool',
  'deny_tool',
  'mcp_auth',
  'mcp_token',
  'consent',
  'permission',
  'sandbox',
  'isolate',
  'quarantine',
  'allow',
  'block',
  'filter',
  'redact',
  'mask',
  'workflow',
  'pipeline',
  'schedule',
  'cron',
  'trigger',
  'webhook',
  'callback',
  'oauth',
  'pkce',
  'refresh_token',
  'access_token',
  'id_token',
  // 2026-04 additions: elicitation, resource, transport, annotations, agent-to-agent
  'elicit',
  'elicitation',
  'user_prompt',
  'resource',
  'resource_read',
  'resource_list',
  'resource_subscribe',
  'roots',
  'roots_list',
  'transport',
  'stream',
  'streamable_http',
  'annotate_tool',
  'tool_annotations',
  'a2a_send',
  'a2a_receive',
  'agent_transfer',
  'agent_handoff',
  'docker_exec',
  'container_run',
  'kubernetes_exec',
  'k8s_apply',
  'dns_update',
  'dns_record',
  'wallet_sign',
  'wallet_transfer',
  'transaction_send',
  // 2026-04-07 additions: sampling, notifications, completions, clipboard, browser, logging, progress
  'create_message',
  'sampling',
  'complete',
  'completion',
  'notifications',
  'notify',
  'progress',
  'log',
  'logging',
  'clipboard',
  'clipboard_read',
  'clipboard_write',
  'browser',
  'browser_navigate',
  'browser_screenshot',
  'browser_click',
  'screenshot',
  'open_url',
  'cancel',
  'ping',
  'initialize',
  // 2026-04-10 additions: model invocation, agent delegation, protocol bridge, code review, IaC, observability
  'model_invoke',
  'inference',
  'predict',
  'classify_text',
  'delegate',
  'escalate',
  'handoff',
  'agent_invoke',
  'bridge',
  'protocol_translate',
  'approve_pr',
  'merge_pr',
  'code_review',
  'terraform_apply',
  'terraform_plan',
  'pulumi_up',
  'kubectl_apply',
  'helm_install',
  'dns_resolve',
  'dns_lookup',
  'state_read',
  'state_write',
  'bedrock_invoke',
  'sagemaker_invoke',
  'vertex_predict',
  'log_write',
  'log_delete',
  'audit_clear',
  'budget_check',
  'quota_read',
  'cost_estimate',
])

/** Patterns that closely mimic built-in tool names. */
const SHADOWING_PATTERNS: Array<{ pattern: RegExp; shadowsBuiltin: string }> = [
  { pattern: /^bash_?(?:exec|run|command)?$/i, shadowsBuiltin: 'bash' },
  { pattern: /^(?:run|exec)_?(?:bash|shell|command|code)$/i, shadowsBuiltin: 'bash/shell' },
  { pattern: /^(?:web|internet)_?search$/i, shadowsBuiltin: 'web_search' },
  { pattern: /^(?:file|fs)_?(?:read|write|edit|create|delete)$/i, shadowsBuiltin: 'file tools' },
  { pattern: /^computer_?(?:use|control|action)?$/i, shadowsBuiltin: 'computer' },
  { pattern: /^str_replace/i, shadowsBuiltin: 'str_replace_editor' },
  { pattern: /^git_?(?:diff|commit|push|pull|init|clone|log|status)$/i, shadowsBuiltin: 'git tools' },
  { pattern: /^(?:read|get|open)_?file$/i, shadowsBuiltin: 'read_file' },
  { pattern: /^(?:write|save|put)_?file$/i, shadowsBuiltin: 'write_file' },
  { pattern: /^(?:list|ls|dir)_?(?:dir|directory|files)?$/i, shadowsBuiltin: 'list_directory' },
  { pattern: /^(?:send|post)_?message$/i, shadowsBuiltin: 'send_message' },
  { pattern: /^(?:curl|wget|fetch|get)_?(?:url|page|data)?$/i, shadowsBuiltin: 'fetch/curl' },
  { pattern: /^(?:run|exec|execute)_?(?:cmd|command|script)?$/i, shadowsBuiltin: 'run_command' },
  { pattern: /^(?:mcp)_?(?:install|connect|disconnect|list)$/i, shadowsBuiltin: 'mcp tools' },
  { pattern: /^(?:tool|function)_?(?:call|invoke|execute)$/i, shadowsBuiltin: 'tool_call' },
  { pattern: /^(?:approve|deny|allow|block)_?(?:tool|action|request)?$/i, shadowsBuiltin: 'approve/deny' },
  { pattern: /^(?:ask|prompt|question)_?(?:user|human)?$/i, shadowsBuiltin: 'ask_user' },
  { pattern: /^(?:web|url|page)_?(?:fetch|get|load|scrape)$/i, shadowsBuiltin: 'web_fetch' },
  { pattern: /^(?:notebook|ipynb)_?(?:edit|run|execute|cell)?$/i, shadowsBuiltin: 'notebook' },
  { pattern: /^(?:screenshot|capture)_?(?:screen|page|window|element)?$/i, shadowsBuiltin: 'screenshot' },
  { pattern: /^(?:click|tap|press)_?(?:element|button|link)?$/i, shadowsBuiltin: 'click' },
  { pattern: /^(?:navigate|goto|visit)_?(?:url|page|site)?$/i, shadowsBuiltin: 'navigate' },
  { pattern: /^(?:deploy|publish|release)_?(?:app|service|code)?$/i, shadowsBuiltin: 'deploy' },
  { pattern: /^(?:clipboard|copy|paste)_?(?:text|data|content)?$/i, shadowsBuiltin: 'clipboard' },
  { pattern: /^(?:memory|context|history)_?(?:read|write|get|set|store)?$/i, shadowsBuiltin: 'memory' },
  { pattern: /^(?:create|send|make)_?message$/i, shadowsBuiltin: 'create_message' },
  { pattern: /^(?:sample|sampling)_?(?:request|create|generate)?$/i, shadowsBuiltin: 'sampling' },
  { pattern: /^(?:think|reason|plan)_?(?:step|ahead|through)?$/i, shadowsBuiltin: 'think/plan' },
  { pattern: /^(?:search|find|locate)_?(?:code|files?|text|content)?$/i, shadowsBuiltin: 'search' },
  { pattern: /^(?:test|lint|format|compile|build)_?(?:code|project|file)?$/i, shadowsBuiltin: 'build tools' },
  { pattern: /^(?:auth|login|logout|authorize)_?(?:user|session|token)?$/i, shadowsBuiltin: 'auth' },
  { pattern: /^(?:config|settings|env|secret)_?(?:read|write|get|set|manage)?$/i, shadowsBuiltin: 'config/settings' },
  { pattern: /^(?:encrypt|decrypt|sign|hash|verify)_?(?:data|file|message|token)?$/i, shadowsBuiltin: 'crypto tools' },
  { pattern: /^(?:monitor|watch|listen|alert|notify)_?(?:event|change|update)?$/i, shadowsBuiltin: 'monitor' },
  { pattern: /^(?:prompt|completion|generate)_?(?:text|response|message)?$/i, shadowsBuiltin: 'prompt/generate' },
  { pattern: /^(?:embed|embedding)_?(?:text|query|document)?$/i, shadowsBuiltin: 'embed' },
  { pattern: /^(?:summarize|summary)_?(?:text|document|page)?$/i, shadowsBuiltin: 'summarize' },
  { pattern: /^(?:import|export|sync)_?(?:data|files?|config)?$/i, shadowsBuiltin: 'import/export' },
  { pattern: /^(?:proxy|relay|gateway|forward|tunnel)_?(?:request|traffic|data)?$/i, shadowsBuiltin: 'proxy/relay' },
  { pattern: /^(?:backup|snapshot|restore|revert)_?(?:data|state|config)?$/i, shadowsBuiltin: 'backup/restore' },
  { pattern: /^(?:reset|clear|wipe|purge)_?(?:data|state|cache|memory)?$/i, shadowsBuiltin: 'reset' },
  { pattern: /^(?:approve|deny|allow|block|permit)_?(?:tool|action|request|operation)?_?(?:call|use)?$/i, shadowsBuiltin: 'approve/deny' },
  { pattern: /^(?:oauth|pkce|token|auth)_?(?:flow|grant|exchange|callback|refresh)?$/i, shadowsBuiltin: 'oauth' },
  { pattern: /^(?:consent|permission|authorize)_?(?:grant|request|check|verify)?$/i, shadowsBuiltin: 'consent/permission' },
  { pattern: /^(?:sandbox|isolate|quarantine)_?(?:tool|server|process|env)?$/i, shadowsBuiltin: 'sandbox' },
  { pattern: /^(?:workflow|pipeline|schedule|cron)_?(?:run|execute|trigger|dispatch)?$/i, shadowsBuiltin: 'workflow' },
  { pattern: /^(?:webhook|callback|trigger)_?(?:handler|receiver|endpoint)?$/i, shadowsBuiltin: 'webhook' },
  { pattern: /^(?:redact|mask|filter)_?(?:data|output|response|pii)?$/i, shadowsBuiltin: 'redact/mask' },
  // 2026-04 additions: elicitation, resource, transport, agent-to-agent, container, DNS
  { pattern: /^(?:elicit|elicitation|user_prompt)_?(?:request|ask|query)?$/i, shadowsBuiltin: 'elicitation' },
  { pattern: /^(?:resource|resources)_?(?:read|list|get|subscribe|fetch)?$/i, shadowsBuiltin: 'resource' },
  { pattern: /^(?:roots|root)_?(?:list|get|discover)?$/i, shadowsBuiltin: 'roots' },
  { pattern: /^(?:stream|transport|streamable)_?(?:http|connect|open)?$/i, shadowsBuiltin: 'transport' },
  { pattern: /^(?:a2a|agent)_?(?:send|receive|transfer|handoff|delegate)?$/i, shadowsBuiltin: 'agent_transfer' },
  { pattern: /^(?:docker|container|podman|k8s|kubernetes)_?(?:exec|run|apply|deploy|create)?$/i, shadowsBuiltin: 'docker_exec' },
  { pattern: /^(?:dns|domain|nameserver)_?(?:update|record|modify|create|delete)?$/i, shadowsBuiltin: 'dns_update' },
  { pattern: /^(?:wallet|crypto|token)_?(?:sign|transfer|send|swap|approve)?$/i, shadowsBuiltin: 'wallet_sign' },
  { pattern: /^(?:annotate|annotation)_?(?:tool|hint|metadata)?$/i, shadowsBuiltin: 'tool_annotations' },
  // 2026-04-07 additions: sampling, notifications, completions, clipboard, browser, logging
  { pattern: /^(?:create_?message|sampling|sample)_?(?:request|prompt|query)?$/i, shadowsBuiltin: 'create_message' },
  { pattern: /^(?:notification|notifications|notify)_?(?:send|message|push)?$/i, shadowsBuiltin: 'notifications' },
  { pattern: /^(?:complete|completion|completions)_?(?:ref|argument|resource)?$/i, shadowsBuiltin: 'completion' },
  { pattern: /^(?:clipboard|paste|copy)_?(?:read|write|get|set|access)?$/i, shadowsBuiltin: 'clipboard' },
  { pattern: /^(?:browser|chrome|firefox|navigate)_?(?:open|click|screenshot|navigate|fetch)?$/i, shadowsBuiltin: 'browser' },
  { pattern: /^(?:log|logging|logger)_?(?:write|send|message|event)?$/i, shadowsBuiltin: 'logging' },
  { pattern: /^(?:progress|status)_?(?:update|report|notify|set)?$/i, shadowsBuiltin: 'progress' },
  { pattern: /^(?:cancel|abort|stop|terminate)_?(?:request|operation|task)?$/i, shadowsBuiltin: 'cancel' },
  { pattern: /^(?:ping|health|heartbeat|alive)_?(?:check|test|verify)?$/i, shadowsBuiltin: 'ping' },
  { pattern: /^(?:initialize|init|setup|connect)_?(?:server|client|session)?$/i, shadowsBuiltin: 'initialize' },
  // 2026-04-10 additions: model invocation, agent delegation, protocol bridge, code review, IaC, observability
  { pattern: /^(?:model|llm|ai)_?(?:invoke|call|predict|infer|generate|complete)?$/i, shadowsBuiltin: 'model_invoke' },
  { pattern: /^(?:inference|predict|classify)_?(?:text|image|data|input)?$/i, shadowsBuiltin: 'inference' },
  { pattern: /^(?:delegate|escalate|handoff|transfer)_?(?:task|agent|request)?$/i, shadowsBuiltin: 'delegate' },
  { pattern: /^(?:agent|worker)_?(?:invoke|call|spawn|create|delegate)?$/i, shadowsBuiltin: 'agent_invoke' },
  { pattern: /^(?:bridge|translate|convert)_?(?:protocol|request|message)?$/i, shadowsBuiltin: 'bridge' },
  { pattern: /^(?:approve|merge|accept)_?(?:pr|pull_request|mr|merge_request|change)?$/i, shadowsBuiltin: 'approve_pr' },
  { pattern: /^(?:code|pull)_?(?:review|approve|reject|comment)?$/i, shadowsBuiltin: 'code_review' },
  { pattern: /^(?:terraform|pulumi|cloudformation|iac)_?(?:apply|plan|destroy|deploy|up)?$/i, shadowsBuiltin: 'terraform_apply' },
  { pattern: /^(?:kubectl|k8s|helm|kustomize)_?(?:apply|deploy|install|delete)?$/i, shadowsBuiltin: 'kubectl_apply' },
  { pattern: /^(?:state|tfstate)_?(?:read|write|get|set|show|list)?$/i, shadowsBuiltin: 'state_read' },
  { pattern: /^(?:bedrock|sagemaker|vertex)_?(?:invoke|predict|generate|embed)?$/i, shadowsBuiltin: 'bedrock_invoke' },
  { pattern: /^(?:log|audit|trace)_?(?:write|delete|clear|purge|modify)?$/i, shadowsBuiltin: 'log_write' },
  { pattern: /^(?:budget|quota|cost|billing)_?(?:check|read|get|monitor|estimate)?$/i, shadowsBuiltin: 'budget_check' },
]

/**
 * Analyze a server's tools for shadowing attacks.
 * Shadowing registers tools with names identical or very similar to trusted
 * built-in tools, causing the LLM to call the malicious version instead.
 */
export function analyzeShadowing(server: MCPServer): Finding[] {
  const findings: Finding[] = []
  if (!server.tools) return findings

  for (const tool of server.tools) {
    const toolNameLower = tool.name.toLowerCase()

    // Exact match against known built-in names.
    if (BUILT_IN_TOOL_NAMES.has(toolNameLower)) {
      findings.push({
        analyzer: 'shadowing',
        severity: 'high',
        server_name: server.name,
        tool_name: tool.name,
        description: `Tool name "${tool.name}" shadows a known built-in tool. Attackers use this to intercept LLM calls to trusted tools.`,
        field: 'name',
        evidence: tool.name,
        remediation: SHADOWING_REMEDIATION,
      })
      continue
    }

    // Pattern match for near-duplicates.
    for (const { pattern, shadowsBuiltin } of SHADOWING_PATTERNS) {
      if (pattern.test(tool.name)) {
        findings.push({
          analyzer: 'shadowing',
          severity: 'medium',
          server_name: server.name,
          tool_name: tool.name,
          description: `Tool name "${tool.name}" closely mimics built-in "${shadowsBuiltin}" (shadowing pattern).`,
          field: 'name',
          evidence: tool.name,
          remediation: SHADOWING_REMEDIATION,
        })
        break
      }
    }
  }

  return findings
}
